"use client";

import { useState } from "react";
import { createBrowserSupabaseClient } from "../../lib/supabase/browser";
import styles from "./club-dashboard.module.css";

type Reward = { id: string; code: string; title: string; description: string; points_cost: number; stock: number | null };
type Ledger = { id: string; event_type: string; amount: number; occurred_at: string; metadata: Record<string, unknown> };

export default function ClubDashboard({ user, account, rewards, ledger }: { user: { id: string; email: string }; account: { id: string; points_balance: number; tier_code: string } | null; rewards: Reward[]; ledger: Ledger[] }) {
  const [balance, setBalance] = useState(account?.points_balance ?? 0); const [message, setMessage] = useState(""); const [loading, setLoading] = useState<string | null>(null);
  async function redeem(reward: Reward) { setLoading(reward.id); setMessage(""); const response = await fetch("/api/rewards/redeem", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rewardId: reward.id, customerId: user.id, idempotencyKey: crypto.randomUUID() }) }); const body = await response.json(); if (!response.ok) setMessage(body.error ?? "No pudimos procesar el canje."); else { setBalance(value => value - reward.points_cost); setMessage(`¡Listo! Tu canje de “${reward.title}” está pendiente de gestión.`); } setLoading(null); }
  async function signOut() { await createBrowserSupabaseClient().auth.signOut(); window.location.href = "/landing"; }
  return <main className={styles.page}><header><a href="/landing" className={styles.brand}>Bionda <i>y</i> Mora</a><div><span>{user.email}</span><button onClick={signOut}>Cerrar sesión</button></div></header><section className={styles.hero}><div><p className={styles.eyebrow}>TU CLUB</p><h1>Hola.<br /><em>Tu camino sigue sumando.</em></h1></div><article className={styles.balance}><p>PUNTOS DISPONIBLES</p><strong>{balance.toLocaleString("es-CO")}</strong><span>puntos</span><small>Nivel actual: <b>{account?.tier_code ?? "Esencia"}</b></small></article></section><section className={styles.section}><div><p className={styles.eyebrow}>BANCO DE RECOMPENSAS</p><h2>Elige lo que te acompaña ahora.</h2></div><div className={styles.rewards}>{rewards.map(reward => <article key={reward.id}><p>{reward.code.replaceAll("_", " ")}</p><h3>{reward.title}</h3><span>{reward.description}</span><footer><b>{reward.points_cost.toLocaleString("es-CO")} puntos</b><button disabled={loading === reward.id || balance < reward.points_cost || reward.stock === 0} onClick={() => redeem(reward)}>{loading === reward.id ? "Procesando…" : balance < reward.points_cost ? "Aún no disponible" : "Redimir ↗"}</button></footer></article>)}</div>{message && <p className={styles.message} role="status">{message}</p>}</section><section className={`${styles.section} ${styles.history}`}><div><p className={styles.eyebrow}>TU HISTORIAL</p><h2>Todo lo que has recorrido.</h2></div>{ledger.length ? <ul>{ledger.map(item => <li key={item.id}><span>{item.event_type === "redeem" ? "↗" : "✦"}</span><div><b>{item.event_type === "redeem" ? "Canje de recompensa" : "Puntos obtenidos"}</b><small>{new Intl.DateTimeFormat("es-CO", { dateStyle: "medium" }).format(new Date(item.occurred_at))}</small></div><strong className={item.amount < 0 ? styles.negative : styles.positive}>{item.amount > 0 ? "+" : ""}{item.amount.toLocaleString("es-CO")} puntos</strong></li>)}</ul> : <p className={styles.empty}>Tu historial aparecerá cuando recibamos tu primera compra o misión.</p>}</section></main>;
}
