import Image from "next/image";
import Link from "next/link";
import styles from "./landing.module.css";
import entryStyles from "./entry.module.css";

const benefits = ["Puntos por compras y acciones verificadas", "Tarjetas de regalo y detalles por desbloquear", "Un camino hacia tus próximas botas"];

export default function LandingPage() {
  return <main className={`${styles.scope} landing`}>
    <div className="landing-promise"><span>Envío gratis desde $350.000</span><span>Cuero 100% legítimo, hecho en Colombia</span><span>Cambios de talla sin costo por 30 días</span></div>
    <header className="landing-nav"><Link href="/landing" className="landing-brand">Bionda <i>y</i> Mora</Link><nav><a href="#como-funciona">Cómo funciona</a><a href="#beneficios">Beneficios</a><Link href="/registro">Entrar al Club</Link></nav></header>
    <section className="landing-hero"><Image src="/brand/hero.jpg" alt="Pieza Bionda y Mora en cuero" fill priority sizes="100vw" /><div className="landing-shade" /><div className="landing-hero-content"><p>HECHAS PARA TI · VISTA PREVIA DEL CLUB</p><h1>Comodidad en<br /><em>cada paso.</em></h1><span>Explora el Club que estamos preparando: tus elecciones y gestos podrán transformarse en beneficios hechos para acompañarte.</span><Link href="/registro" className="landing-cta">Conoce la demo <b>→</b></Link></div><div className="landing-seal">HECHO EN<br />COLOMBIA<br />✦</div></section>
    <section className="landing-intro" id="como-funciona"><p className="landing-label">HECHO PARA ACOMPAÑARTE · VISTA PREVIA</p><h2>Una forma más bonita<br />de volver a elegirte.</h2><p className="landing-description">Puedes conocer el Club después de comprar, de encontrarnos en una feria o de suscribirte a nuestras novedades en la web. Cada historia empieza en un lugar distinto.</p><div className="landing-steps">{["Elige cómo llegaste", "Descubre cómo avanzar", "Explora recompensas"].map((step, index) => <article key={step}><span>0{index + 1}</span><h3>{step}</h3><p>{index === 0 ? "Compra, encuentro o suscripción: hay un comienzo para ti." : index === 1 ? "Conoce acciones que tienen sentido para tu momento." : "Mira los beneficios y simula un canje."}</p></article>)}</div></section>
    <section className={entryStyles.entry} aria-labelledby="entry-title"><div><p className="landing-label">UNA TERCERA FORMA DE LLEGAR</p><h2 id="entry-title">¿Nos conociste por correo?</h2><p>Si te suscribiste a las novedades de Bionda y Mora, también puedes comenzar en el Club. No necesitas haber comprado: explora piezas, elige lo que te inspira y descubre qué acciones suman después de verificarse.</p><small>Recibir marketing no da puntos ni es obligatorio para conservar tu membresía.</small></div><Link href="/registro?origen=web">Entrar desde mi suscripción <b aria-hidden="true">↗</b></Link></section>
    <section className="landing-story" id="beneficios"><div className="landing-story-image"><Image src="/brand/atelier.jpg" alt="Mujeres Bionda y Mora caminando con botas de cuero" fill sizes="(max-width: 800px) 100vw, 45vw" /></div><div className="landing-story-copy"><p className="landing-label">EL CLUB · EN PREPARACIÓN</p><h2>Más que puntos,<br /><em>un gesto para ti.</em></h2><p>Próximamente podrás acceder primero, descubrir nuevas piezas y transformar tus puntos en recompensas. Por ahora, conoce la experiencia sin crear beneficios reales.</p><ul>{benefits.map(benefit => <li key={benefit}>✦ <span>{benefit}</span></li>)}</ul><Link href="/registro" className="landing-text-link">Explorar beneficios ↗</Link></div></section>
    <section className="landing-gallery"><Image src="/brand/collection.jpg" alt="Colección Bionda y Mora" width={600} height={760} /><Image src="/brand/look.jpg" alt="Look Bionda y Mora" width={600} height={760} /><Image src="/brand/ribuzz/product-02.jpg" alt="Producto Bionda y Mora" width={600} height={760} /></section>
    <section className="landing-final"><p className="landing-label">CLUB BIONDA Y MORA</p><h2>Camina con nosotras.</h2><Link href="/registro" className="landing-cta dark">Entrar al Club <b>→</b></Link></section>
  </main>;
}
